### ISSUE TITLE
Speed issue with VariableTree being deep copied

### ISSUE THREAD

**Issue by rethore** [FUSED-Wind/fusedwind#12]
When a VariableTree is passed as a static input to a component in a CaseIteratorDriver, it is systematically deep-copied. This creates a significant overhead that scales with the number and size of variables within the VariableTree. A wind farm AEP calculation with 600 flow cases (wind speed and direction) takes easily more than a minute on a full size wind farm --just to deep copy the same VariableTree.

OpenMDAO is working on a next release that has had some significant changes on how to handle VariableTrees, with "dramatic speed improvement". Hopefully this performance issue is also dealt with.

### TODO:
- [x] contact openMDAO team
- [ ] make a reduce problem for them to test on
- [ ] follow up on the bug report

**Comment by dykesk** [comment]
closing - openmdao undergoing refactoring and will revisit speed with new version release
