### ISSUE TITLE
debugging wake

### ISSUE THREAD

**Issue by rethore** [FUSED-Wind/fusedwind#19]
The plant_flow.wake is currently not operational. This issue is aiming at getting all the existing tests to run smoothly.
### TODO:
- [x] fixing lib_test.py
- [ ] fixing test_NOJ.py
- [x] removing test_fused_wake.py
- [x] fixing test_wake.py

**Comment by rethore** [comment]
I moved the wake into DTUWindEnergy/FUSED-Wake for now. If somebody else thinks it should come back to FUSEDWind let me know.
